"""empty message

Revision ID: 21fe53397af7
Revises: c68103c0ef5e
Create Date: 2020-05-19 10:33:07.209676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21fe53397af7'
down_revision = 'c68103c0ef5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=128), nullable=True))
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'name')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=128), nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'user', ['user_id'], ['id'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
