"""empty message

Revision ID: 549457416199
Revises: 6923958775d4
Create Date: 2020-06-08 10:14:02.834067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '549457416199'
down_revision = '6923958775d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'prof_bonus')
    op.drop_column('character', 'spell_save')
    op.drop_column('character', 'spell_attack')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('spell_attack', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('character', sa.Column('spell_save', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('character', sa.Column('prof_bonus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
