"""empty message

Revision ID: 6923958775d4
Revises: 71444ba42484
Create Date: 2020-06-06 21:44:29.958683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6923958775d4'
down_revision = '71444ba42484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deck', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('m_player', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_player', 'is_active')
    op.drop_column('deck', 'is_active')
    # ### end Alembic commands ###
