"""empty message

Revision ID: 69475a5a4c15
Revises: 
Create Date: 2020-05-25 23:34:53.170927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69475a5a4c15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.Text(length=30000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('cast_time', sa.String(length=128), nullable=True),
    sa.Column('concentration', sa.Boolean(), nullable=True),
    sa.Column('ritual', sa.Boolean(), nullable=True),
    sa.Column('spell_range', sa.String(length=128), nullable=True),
    sa.Column('components', sa.String(length=500), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.Column('school', sa.String(length=128), nullable=True),
    sa.Column('info', sa.String(length=5000), nullable=True),
    sa.Column('from_book', sa.String(length=128), nullable=True),
    sa.Column('is_bard', sa.Boolean(), nullable=True),
    sa.Column('is_cleric', sa.Boolean(), nullable=True),
    sa.Column('is_druid', sa.Boolean(), nullable=True),
    sa.Column('is_paladin', sa.Boolean(), nullable=True),
    sa.Column('is_ranger', sa.Boolean(), nullable=True),
    sa.Column('is_sorcerer', sa.Boolean(), nullable=True),
    sa.Column('is_warlock', sa.Boolean(), nullable=True),
    sa.Column('is_wizard', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('race', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('class_resource', sa.Integer(), nullable=True),
    sa.Column('saving_throw', sa.String(length=128), nullable=True),
    sa.Column('ability_score', sa.Integer(), nullable=True),
    sa.Column('spell_save', sa.Integer(), nullable=True),
    sa.Column('spell_attack', sa.Integer(), nullable=True),
    sa.Column('prof_bonus', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=5000), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('body', sa.String(length=5000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.Column('max_val', sa.Integer(), nullable=True),
    sa.Column('cur_val', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('spellbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.Column('prepared', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spellbook')
    op.drop_table('slots')
    op.drop_table('note')
    op.drop_table('subclass')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('spell')
    op.drop_table('class')
    # ### end Alembic commands ###
