"""empty message

Revision ID: 7466ebad4389
Revises: d38b1075d1fa
Create Date: 2020-06-04 23:00:38.348559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7466ebad4389'
down_revision = 'd38b1075d1fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slots_ibfk_1', 'slots', type_='foreignkey')
    op.create_foreign_key(None, 'slots', 'character', ['char_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.create_foreign_key('slots_ibfk_1', 'slots', 'character', ['char_id'], ['id'])
    # ### end Alembic commands ###
