"""empty message

Revision ID: b22a06e8023b
Revises: 60a416d26b35
Create Date: 2020-05-21 19:08:53.920710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22a06e8023b'
down_revision = '60a416d26b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('character_ibfk_1', 'character', type_='foreignkey')
    op.create_foreign_key(None, 'character', 'class', ['class_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.create_foreign_key('character_ibfk_1', 'character', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###
