"""empty message

Revision ID: c68103c0ef5e
Revises: 1a82f64ebbf1
Create Date: 2020-05-19 10:30:12.414958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c68103c0ef5e'
down_revision = '1a82f64ebbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
