"""empty message

Revision ID: ccbb7e5e4019
Revises: 21fe53397af7
Create Date: 2020-05-19 22:49:18.593717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbb7e5e4019'
down_revision = '21fe53397af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=5000), nullable=True),
    sa.Column('resource_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=5000), nullable=True),
    sa.Column('resource', sa.Integer(), nullable=True),
    sa.Column('saving_throw', sa.String(length=128), nullable=True),
    sa.Column('spell_save', sa.Integer(), nullable=True),
    sa.Column('spell_attack', sa.Integer(), nullable=True),
    sa.Column('prof_bonus', sa.Integer(), nullable=True),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['subclass.id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('slots',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('lvl_1', sa.Integer(), nullable=True),
    sa.Column('lvl_2', sa.Integer(), nullable=True),
    sa.Column('lvl_3', sa.Integer(), nullable=True),
    sa.Column('lvl_4', sa.Integer(), nullable=True),
    sa.Column('lvl_5', sa.Integer(), nullable=True),
    sa.Column('lvl_6', sa.Integer(), nullable=True),
    sa.Column('lvl_7', sa.Integer(), nullable=True),
    sa.Column('lvl_8', sa.Integer(), nullable=True),
    sa.Column('lvl_9', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    op.drop_table('class')
    op.drop_table('subclass')
    op.drop_table('spell')
    # ### end Alembic commands ###
