"""empty message

Revision ID: d8116c7e6a61
Revises: 9d94589e1aa9
Create Date: 2020-05-22 16:26:24.697857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8116c7e6a61'
down_revision = '9d94589e1aa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('note_ibfk_1', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'character', ['char_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_ibfk_1', 'note', 'character', ['char_id'], ['id'])
    # ### end Alembic commands ###
