"""empty message

Revision ID: d9204973eb73
Revises: fbbb97e92758
Create Date: 2020-06-04 22:47:32.782142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9204973eb73'
down_revision = 'fbbb97e92758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('lvl', sa.Integer(), nullable=True))
    op.add_column('slots', sa.Column('res', sa.Integer(), nullable=True))
    op.drop_column('slots', 'cur_val')
    op.drop_column('slots', 'max_val')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('max_val', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('slots', sa.Column('cur_val', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('slots', 'res')
    op.drop_column('slots', 'lvl')
    # ### end Alembic commands ###
