"""empty message

Revision ID: e860d3c543fb
Revises: dce8d5d420f1
Create Date: 2020-05-20 09:39:38.494887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e860d3c543fb'
down_revision = 'dce8d5d420f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subclass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('desc', sa.String(length=5000), nullable=True),
    sa.Column('resource_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('race', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('char_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=5000), nullable=True),
    sa.Column('resource', sa.Integer(), nullable=True),
    sa.Column('saving_throw', sa.String(length=128), nullable=True),
    sa.Column('ability_score', sa.Integer(), nullable=True),
    sa.Column('spell_save', sa.Integer(), nullable=True),
    sa.Column('spell_attack', sa.Integer(), nullable=True),
    sa.Column('prof_bonus', sa.Integer(), nullable=True),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['subclass_id'], ['subclass.id'], ),
    sa.PrimaryKeyConstraint('char_id')
    )
    op.create_table('slots',
    sa.Column('slot_id', sa.String(length=128), nullable=False),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.Column('lvl', sa.Integer(), nullable=True),
    sa.Column('max_val', sa.Integer(), nullable=True),
    sa.Column('cur_val', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('spellbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('char_id', sa.Integer(), nullable=True),
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.Column('prepared', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['char_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['spell_id'], ['spell.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spellbook')
    op.drop_table('slots')
    op.drop_table('class')
    op.drop_table('character')
    op.drop_table('user')
    op.drop_table('subclass')
    op.drop_table('spell')
    # ### end Alembic commands ###
