"""empty message

Revision ID: eec18831db16
Revises: 69475a5a4c15
Create Date: 2020-06-03 18:29:35.622747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eec18831db16'
down_revision = '69475a5a4c15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('scaling', sa.String(length=5000), nullable=True))
    op.drop_column('spell', 'ritual')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('ritual', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('spell', 'scaling')
    # ### end Alembic commands ###
