"""empty message

Revision ID: fbbb97e92758
Revises: f25865a2c19f
Create Date: 2020-06-04 22:36:08.690323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbbb97e92758'
down_revision = 'f25865a2c19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('casting_ability', sa.String(length=128), nullable=True))
    op.drop_column('character', 'saving_throw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('saving_throw', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('character', 'casting_ability')
    # ### end Alembic commands ###
