"""empty message

Revision ID: ff3594f07908
Revises: b22a06e8023b
Create Date: 2020-05-21 21:51:20.711761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3594f07908'
down_revision = 'b22a06e8023b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spell', sa.Column('cast_time', sa.String(length=128), nullable=True))
    op.add_column('spell', sa.Column('components', sa.String(length=128), nullable=True))
    op.add_column('spell', sa.Column('duration', sa.String(length=128), nullable=True))
    op.add_column('spell', sa.Column('from_book', sa.String(length=128), nullable=True))
    op.add_column('spell', sa.Column('info', sa.String(length=5000), nullable=True))
    op.add_column('spell', sa.Column('is_bard', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('is_cleric', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('is_druid', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('is_paladin', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('is_ranger', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('is_sorcerer', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('is_warlock', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('is_wizard', sa.Boolean(), nullable=True))
    op.add_column('spell', sa.Column('level', sa.Integer(), nullable=True))
    op.add_column('spell', sa.Column('school', sa.String(length=128), nullable=True))
    op.add_column('spell', sa.Column('spell_range', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spell', 'spell_range')
    op.drop_column('spell', 'school')
    op.drop_column('spell', 'level')
    op.drop_column('spell', 'is_wizard')
    op.drop_column('spell', 'is_warlock')
    op.drop_column('spell', 'is_sorcerer')
    op.drop_column('spell', 'is_ranger')
    op.drop_column('spell', 'is_paladin')
    op.drop_column('spell', 'is_druid')
    op.drop_column('spell', 'is_cleric')
    op.drop_column('spell', 'is_bard')
    op.drop_column('spell', 'info')
    op.drop_column('spell', 'from_book')
    op.drop_column('spell', 'duration')
    op.drop_column('spell', 'components')
    op.drop_column('spell', 'cast_time')
    # ### end Alembic commands ###
